import { Poppins } from 'next/font/google';
import '.././globals.css';

const poppins = Poppins({
  weight: ['200', '300', '400', '500', '600', '700', '800'],
  subsets: ["latin"]
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
